### ISSUE TITLE
Claremont link on contact page is broken (404)

### ISSUE THREAD

**Issue by charlieegan3** [unboxed/ubxd_web_refresh#194]
Cape Town nearest station link is: http://www.capemetrorail.co.za/Route-Map.html which is a 404.

Not sure what the replacement should be.

**Comment by richarcher** [comment]
@charlieegan3 possible options: http://gometroapp.com/?transit+index or http://cttrains.co.za/ss_route_select.php

Neither particularly _great_, but at least it's not a 404.

**Comment by mybits** [comment]
Thanks! Solved in 89ffa37
